[package]
name = "cs2-dumper"
version = "1.0.9"
authors = ["a2x"]
edition = "2021"
repository = "https://github.com/a2x/cs2-dumper"
license = "MIT"

[dependencies]
chrono = "0.4"
clap = { version = "4.4", features = ["derive"] }
log = "0.4"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "4.2"
thiserror = "1.0"

[dependencies.windows]
version = "0.51"
features = [
    "Win32_Foundation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_SystemInformation",
    "Win32_System_SystemServices",
    "Win32_System_Threading",
]

[profile.release]
strip = true
